project:
  type: book
  output-dir: book

book:
  title: "Escola de Computação Paralela: Minicursos e Tutoriais"
  author: "Rogério Aparecido Gonçalves (rogerioag@utfpr.edu.br) e João Fabrício Filho (joaof@utfpr.edu.br)"
  cover-image: images/cover.png
  site-url: https://rogerioag.github.io/ecp-minicursos
  repo-url: https://github.com/rogerioag/ecp-minicursos
  repo-branch: master
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - preface.qmd
    - intro.qmd
    - part: pthreads-resumo.qmd
      chapters:
        - pthreads.qmd
    - part: opemp-resumo.qmd
      chapters:
        - openmp.qmd
    - part: simd-resumo.qmd
      chapters:
        - simd.qmd
    - part: cuda-resumo.qmd
      chapters:
        - cuda.qmd
    - part: pytorch-resumo.qmd
      chapters:
        - pytorch.qmd
    - part: llvm-resumo.qmd
      chapters:
        - llvm.qmd
    - part: freertos-resumo.qmd
      chapters:
        - freertos.qmd
    - part: quantica-resumo.qmd
      chapters:
        - quantica.qmd
    - part: comp-dist-resumo.qmd
      chapters:
        - comp-dist.qmd
    - references.qmd
  appendices:
    - a1.qmd

citeproc: true
bibliography: references.bib
bibliographystyle: apa
# csl: https://www.zotero.org/styles/apa-with-abstract

format:
  html:
    theme: cosmo
    cover-image: images/cover.png
    code-link: true

# filters:
# - multibib
validate-yaml: false
