---
description-meta: |
  Este livro irá te ensinar algumas técnicas do Computação Paralela.
---

## Bem-vindo {.unnumbered}

Este livro reune o material dos Minicursos preparados e ministrados no contexto do __Projeto Escola de Computação Paralela (ECP)__. Nele apresentamos minicursos sobre alguns assuntos importantes na Computação Paralela, como __Pthreads__, __Vetorização__, __OpenMP__ e __LLVM__.

## Contribuidores

| Nome | E-mail | Categoria | Minicurso/Tema |
| ------------- | ------------- | ------- | ------- |
| Rogério Aparecido Gonçalves | rogerioag@utfpr.edu.br             | Docente | Coordenador      |
| Joao Fabrício Filho        | joaof@utfpr.edu.br                 | Docente | Vice-Coordenador |
| Guilherme A. Lopes          | guiguigui098@gmail.com             | Aluno   | Vetorização |
| Paulo H. P. da Silva        | phps6200@gmail.com                 | Aluno   | OpenMP |
| William W. T. Rodrigues     | williamwallace@alunos.utfpr.edu.br | Aluno   | Pthreads; Qiskit |
| Gabriela P. Sereniski       | gabsereniski@gmail.com             | Aluno   | Cluster |
| Gabriel M. L. Pereira       | gabrielmlobato@gmail.com           | Aluno   | IA/pyTorch |
| João Victor Briganti de Oliveira       | joliveira.2022@alunos.utfpr.edu.br           | Aluno   | LLVM |
| Luiz Gustavo Takeda | luiztakeda@alunos.utfpr.edu.br | Aluno | FreeRTOS |

<!--
::: {.callout-note appearance="simple"}
This book was originally created using [bookdown](https://bookdown.org) and published at <https://rstudio-education.github.io/hopr/>. This site is a port of the original book source to the [Quarto](https://quarto.org) publishing system in order to provide an example of it's use.
:::

-->

## Licença

Este material é __livre para o uso__ e está sobre a licença [Creative Commons Attribution-NonCommercial-NoDerivs 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/). 

<!--
If you'd like a **physical copy** of the book, you can order it from [amazon](https://www.amazon.com/Hands-Programming-Write-Functions-Simulations/dp/1449359019); it was published by O'Reilly in July 2014. If you'd like to give back, please consider reporting a typo or leaving a pull request at [github.com/rstudio-education/hopr](https://github.com/rstudio-education/hopr).-->
