# Minicurso: Introdução à Programação Paralela: Vetorização

A evolução do hardware é algo imprescindível para a computação. A cada ano, os avanços nessa área têm possibilitado a execução de aplicações cada vez mais complexas, contribuindo significativamente para o desenvolvimento da computação como um todo.

O ponto alto no aumento do desempenho da computação paralela foi a implementação da arquitetura multi-core, que permitiu a execução de múltiplas tarefas simultaneamente por um único processador. No entanto, para aproveitar esse potencial, é necessário adaptar o software, de modo que ele seja capaz de utilizar o hardware de forma eficiente.

As técnicas de vetorização também são fundamentais para a computação paralela. Por meio das instruções SIMD (Single Instruction, Multiple Data), é possível realizar operações simultâneas em diversas regiões da memória, o que aumenta consideravelmente o desempenho das aplicações.

# Por quê estudar Vetorização ?

A vetorização é extremamente importante nos dias de hoje. Embora os compiladores abstraiam muitos aspectos do funcionamento do hardware, é possível instruí-los a utilizar instruções SIMD (Single Instruction, Multiple Data) para obter ganhos de desempenho em operações matriciais.


O objetivo deste minicurso é ensinar os estudantes a utilizarem operações de vetorização para obter ganhos significativos de desempenho em software.







